### ISSUE TITLE
thanks for the info, i will give it a try

### ISSUE THREAD

**Issue by ldijkman** [jnthas/improv-wifi#10]
thanks for the info, i will give it a try

https://ldijkman.github.io/async-esp-fs-webserver/

ok maybe can get it to work

![Screenshot from 2024-02-25 09-29-27](https://github.com/jnthas/improv-wifi-demo/assets/45427770/b04bb6f0-4516-48b8-8a5b-e9372850203a)
aybe can get it to work

**Comment by ldijkman** [comment]
Thank you very much for your examples

https://youtu.be/tgL_leDr7Ls

**Comment by jnthas** [comment]
Glad to see it worked!
