### ISSUE TITLE
ESP Web Tools and Improv SDK are not compatible on same website

### ISSUE THREAD

**Issue by balloob** [jnthas/improv-wifi#2]
Due to the way the web components work that are used by ESP Web Tools and the Improv SDK, it's not compatible to have both active on the same website.

To see it for yourself: open ESP Web Tools, hit cancel, then open Improv. An error will be logged about `mwc-ripple` already being defined.

The solution is to just use ESP Web Tools. It offers all features of Improv Serial.

**Comment by jnthas** [comment]
Got it. But I would like to have an option to flash locally, using Arduino IDE for example and then configure only wifi via website. This will be a possible real scenario. I will another page just to config then.

**Comment by balloob** [comment]
That's still possible with ESP Web Tools. It will automatically probe for Improv when it opens the dialog for the first time. If the firmware supports Improv, interacting with Improv is shown as an option.

![CleanShot 2023-03-15 at 21 39 31](https://user-images.githubusercontent.com/1444314/225487585-4ecd2704-e1b4-416f-a636-247206133f1b.png)

**Comment by jnthas** [comment]
Right. It makes sense :thinking:
