### ISSUE TITLE
Output example firmware as a single binary

### ISSUE THREAD

**Issue by balloob** [jnthas/improv-wifi#4]
When esptool.py merges binaries, it will set some bits for the target device. ESP Web Tools does not do that. For compatibility with most chips, it's suggested to use esptool.py command to merge binaries: https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-commands.html#merge-binaries-for-flashing-merge-bin

**Comment by jnthas** [comment]
Awsome! I didn't know that. Done.
