### ISSUE TITLE
Wifi Connection Time out

### ISSUE THREAD

**Issue by ZanzyTHEbar** [jnthas/improv-wifi#7]
Hello, great example.

I've been testing this, and i ran into an issue. 

When using your provided binary file, everything works fine. 

However, when i try to build from your source and run that the `Wifi Connection` always times out - and i can't figure out why. 

I've tried everything i can think of - what do i have to do to get the wifi connection stage to complete? 

I'd even be fine with skipping that stage altogether tbh - as i don't need it for my application.

**Comment by balloob** [comment]
The connection stage is not implemented yet: https://github.com/jnthas/improv-wifi-demo/blob/main/src/esp32-wifiimprov/esp32-wifiimprov.ino#L134

**Comment by jnthas** [comment]
Thanks! I'm on it right now!

**Comment by jnthas** [comment]
Folks, could you test it and let me know your feedback. I believe the happy path is working.

**Comment by ZanzyTHEbar** [comment]
Thank you for your prompt response. 

I have no issues with your provided example now - however when i try to implement it into my current project i get the same timeout issue.

Link to the code i am [implementing](https://github.com/lorow/OpenIris/blob/c76bcd35bf4962ba2b93854559a6e578638e6d04/ESP/lib/src/io/Improv/improvHandler.cpp#L17)

**Comment by jnthas** [comment]
After my last commit yesterday, you should be able to see an UNABLE_TO_CONNECT error when it can't connect to wifi network, not Timeout. I don't know, maybe it's related to the method connectWifi() you implemented? Check if the credentials are coming and try to implement a retry like I did with MAX_ATTEMPTS
