### ISSUE TITLE
platformio compatibility

### ISSUE THREAD

**Issue by benutti** [jnthas/improv-wifi#9]
You could make the code platformio compatible by using forward declared functions.

**Comment by jnthas** [comment]
That's a good point. I didn't use PlatformIO for this demo. Please, if you have it done already open a PR and I can merge soon. Thanks for the feedback.

**Comment by beniroquai** [comment]
Hey, I just randomly saw this post. What would be the issue in Platform.io? I guess I got it working by simply adapting the pio folder structure. What would be the issue here?

**Comment by jnthas** [comment]
If I not mistaken, in PIO we have to declare the function before of its implementation. That's what I understand. 
https://community.platformio.org/t/order-of-function-declaration/4546/7
I will close this issue, since it worked for you without any code change. Thanks.
